name = "CooperativeHuntingPkg"
uuid = "bb0a82a8-bea2-4e8b-a7d4-ef513daa3692"
authors = ["taliaborofsky <tborofsky@gmail.com>"]
version = "0.1.0"

[deps]
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
BifurcationKit = "0.4.12"
DifferentialEquations = "7.16.1"
ForwardDiff = "0.10.39"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Measures = "0.3.2"
Plots = "1.40.13"
Polynomials = "4.1.0"
UnPack = "1.0.2"
julia = "1.11.3"
